spring:
  application:
    name: eureka-server
server:
  port: 2000
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:2000/eureka
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
